timeout: 1800s
logsBucket: "gs://${_ARTIFACT_BUCKET_NAME}/cloudbuild-logs/app-${_SERVICE_NAME}-push-request-trigger"
options:
  machineType: 'E2_HIGHCPU_8'
availableSecrets:
  secretManager:
  - versionName: "projects/$PROJECT_ID/secrets/${_SONARQUBE_TOKEN_SECRET_NAME}/versions/latest"
    env: 'SONARQUBE_TOKEN'
steps:
  - id: 'Gradle Build && Publish to SonarQube'
    name: 'openjdk:17'
    entrypoint: bash
    args:
      - "-c"
      - |
        #./gradlew \
        #  -Dsonar.login="$$SONARQUBE_TOKEN" \
        #  -Dsonar.projectKey=${REPO_NAME} \
        #  -Dsonar.projectName=${REPO_NAME} \
        #  -Dsonar.host.url=${_SONARQUBE_HOST} \
        ./gradlew clean build 
    secretEnv: ['SONARQUBE_TOKEN']

  - id: 'build'
    name: "${_GAR_BUILDER_URL}/helm:4.0.0"
    entrypoint: bash
    args:
      - "-c"
      - |
        skaffold build -p dev --interactive=false --file-output=/workspace/artifacts.json

  - id: "Cloud Deploy Release"
    name: "google/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud deploy releases create "${REPO_NAME}--${SHORT_SHA}" \
          --project=$PROJECT_ID \
          --region=${_DEPLOY_REGION} \
          --delivery-pipeline=${REPO_NAME} \
          --gcs-source-staging-dir=gs://${_CLOUD_DEPLOY_SOURCE_BUCKET}/source \
          --build-artifacts=/workspace/artifacts.json
