apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: preference
  importDerivedRoles:
    - user_roles
  rules:
    - actions: ["view"]
      roles:
        - admin
        - reader
      derivedRoles:
        - self
      effect: EFFECT_ALLOW

    - actions: ["update"]
      roles:
        - admin
      derivedRoles:
        - self
      effect: EFFECT_ALLOW
